#!/bin/bash
#PBS -l nodes=2:ppn=20
#PBS -l feature=rhel7 
#PBS -l pmem=4gb 
#PBS -l walltime=01:00:00                # Wall time.
#PBS -N Rmpi                 # Job name.
#PBS -A kzk10_e_g_sc_default
#PBS -o outputFileName                   # Output file.
#PBS -e errorFileName                    # Output error info.

module purge
module load gcc
module load openmpi

##############################################################
NCPU=`wc -l < $PBS_NODEFILE`             # Get number of processors.
NNODES=`uniq $PBS_NODEFILE | wc -l`      # Get the number of nodes.

############## Print info ####################################
echo ------------------------------------------------------
echo ' This job is allocated on '${NCPU}' cpu(s)'
echo 'Job is running on node(s): '
cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: number of nodes is $NNODES
echo PBS: number of processes is $PBS_NP
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------

cd $PBS_O_WORKDIR                         # aciRun.pbs dir.
echo "Starting at"                        # Output starting time info.
date


################ User running code #######################
#$(which mpirun) --hostfile $PBS_NODEFILE -np 1 Rscript Test.R 39
mpirun -np $PBS_NP -machinefile $PBS_NODEFILE Rscript Test.R 39

echo "Run completed at "                  # Output ending info.
date
echo ------------------------------------------------------
###############################################################
